app:
  name: spring-mongo-patrol
  description: This projects demonstrats how how run Spring Boot, Mongo DB

logging:
  file: demo.log

server:
  port: 8080

spring:
  data.mongodb.uri: mongodb://172.168.1.250:27017/admin
  spring.mvc:
      static-path-pattern: /static/**
      async.request-timeout: 20000